spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cat?serverTimezone=GMT%2b8
    username: root
    password: 5427wtl.
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
server:
    port: 8888

